# Generated by Django 5.0.7 on 2024-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pollresponse_pollanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='answer',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
